# -*- mode: ruby -*-
# vi: set ft=ruby :

PORT_OFFSET   = (ENV['BOX_PORT_OFFSET'] || 0).to_i
CPUS          = (ENV['BOX_NUM_OF_CPUS'] || 1).to_i.abs
MEMORY        = (ENV['BOX_MEM'] || 512).to_i
INSTALL_NGINX = !ENV['BOX_INSTALL_NGINX'].nil?

ENV['LC_ALL'] = 'en_US.UTF-8'

Vagrant.configure("2") do |config|

  config.vm.synced_folder '../', '/webapp', create: true, group: 'vagrant', owner: 'vagrant'

  config.ssh.insert_key = 'false'

  config.vm.network :forwarded_port, guest: 3000, host: ( 3000 + PORT_OFFSET )
  config.vm.network :forwarded_port, guest: 5432, host: ( 5432 + PORT_OFFSET )
  config.vm.network :forwarded_port, guest: 8080, host: ( 8080 + PORT_OFFSET )

  #####################################
  ##  CentOS  #########################
  #####################################

  config.vm.define "centos", primary: true  do |centos|
    centos.vm.box = "bento/centos-7.2"
    centos.vm.host_name = 'centos'

    centos.vm.provider 'virtualbox' do |vb|
      vb.name = "benchmark-centos"
      vb.memory = MEMORY
      vb.cpus = CPUS
    end

    centos.vm.provision :shell, path: 'centos.sh'
    centos.vm.provision :shell, path: 'install-rvm.sh', args: 'stable', privileged: false
    centos.vm.provision :shell, path: 'install-ruby.sh', args: '2.3.0 rails -v 4.2.7', privileged: false
    centos.vm.provision :shell, path: 'install-postgres-yum.sh'

    if INSTALL_NGINX
      centos.vm.provision :shell, path: 'install-nginx-yum.sh'
    else
      centos.vm.provision :shell, path: 'disable-nginx-yum.sh'
    end

    centos.vm.provision :shell, path: 'post-install.sh', args: '', privileged: false

  end

  #####################################
  ##  Ubuntu ##########################
  #####################################

  config.vm.define "ubuntu",  autostart: false do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.host_name = 'ubuntu'

    ubuntu.vm.provider 'virtualbox' do |vb|
      vb.name = "benchmark-ubuntu"
      vb.memory = MEMORY
      vb.cpus = CPUS
    end

    ubuntu.vm.provision :shell, path: 'ubuntu.sh'
    ubuntu.vm.provision :shell, path: 'install-rvm.sh', args: 'stable', privileged: false
    ubuntu.vm.provision :shell, path: 'install-ruby.sh', args: '2.3.0 rails -v 4.2.7', privileged: false
    ubuntu.vm.provision :shell, path: 'install-postgres-apt.sh', args: '9.5'

    if INSTALL_NGINX
      ubuntu.vm.provision :shell, path: 'install-nginx-apt.sh'
    else
      ubuntu.vm.provision :shell, path: 'disable-nginx-apt.sh'
    end

    ubuntu.vm.provision :shell, path: 'post-install.sh', args: '', privileged: false

  end

end
